"""empty message

Revision ID: d5f69fefb584
Revises: None
Create Date: 2016-03-31 02:46:07.327583

"""

# revision identifiers, used by Alembic.
revision = 'd5f69fefb584'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myprofile', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('myprofile', sa.Column('sex', sa.String(length=8), nullable=True))
    op.create_unique_constraint(None, 'myprofile', ['id_num'])
    op.drop_column('myprofile', u'photo')
    op.drop_column('myprofile', u'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myprofile', sa.Column(u'password', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('myprofile', sa.Column(u'photo', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'myprofile', type_='unique')
    op.drop_column('myprofile', 'sex')
    op.drop_column('myprofile', 'age')
    ### end Alembic commands ###
